### ISSUE TITLE
can the key property be removed from a Sink?

### ISSUE THREAD

**Issue by neonstalwart** [Raynos/event-sinks#3]
once #2 is merged, nothing in this package uses `key` - can it be removed from the Sink interface?

**Comment by Raynos** [comment]
The key cannot be removed.

If you wanted to serialize a sink, i.e. store it in a `dataset` property as a string you want to keep a reference to the key.

**Comment by neonstalwart** [comment]
I'm not sure I follow.., how would you serialize `write`?

**Comment by Raynos** [comment]
@neonstalwart 

You can't serialize all writes generically, however the write used in event-sinks/index.js or event-sinks/geval.js is trivial to serialize / reconstruct.

**Comment by neonstalwart** [comment]
i'm fairly sure this issue is stale.  @Raynos reopen if you think there's something unresolved here.
